// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecimenCheckin.Api.Data;

#nullable disable

namespace SpecimenCheckin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629190049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecimenCheckin.Api.Models.CheckInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpecimenId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("CheckInEvents");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Discrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SpecimenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("Discrepancies");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Code");

                    b.HasIndex("LabId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Specimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ManifestId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.CheckInEvent", b =>
                {
                    b.HasOne("SpecimenCheckin.Api.Models.Manifest", "Manifest")
                        .WithMany("CheckInEvents")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Clinic", b =>
                {
                    b.HasOne("SpecimenCheckin.Api.Models.Lab", "Lab")
                        .WithMany("Clinics")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Discrepancy", b =>
                {
                    b.HasOne("SpecimenCheckin.Api.Models.Manifest", "Manifest")
                        .WithMany("Discrepancies")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecimenCheckin.Api.Models.Specimen", "Specimen")
                        .WithMany("Discrepancies")
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manifest");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Manifest", b =>
                {
                    b.HasOne("SpecimenCheckin.Api.Models.Clinic", "Clinic")
                        .WithMany("Manifests")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecimenCheckin.Api.Models.Lab", "Lab")
                        .WithMany("Manifests")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Specimen", b =>
                {
                    b.HasOne("SpecimenCheckin.Api.Models.Manifest", "Manifest")
                        .WithMany("Specimens")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Clinic", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Lab", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Manifest", b =>
                {
                    b.Navigation("CheckInEvents");

                    b.Navigation("Discrepancies");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("SpecimenCheckin.Api.Models.Specimen", b =>
                {
                    b.Navigation("Discrepancies");
                });
#pragma warning restore 612, 618
        }
    }
}
